#!/usr/bin/env bash
# api-diff-generate.sh
#
# Host-side generation for the API Diff Worker workflow. Given a single discovery target it positions
# the working tree on the branch the agent will publish to (detached at the base for a fresh
# diff, or the maintained PR branch for an incremental update) and generates the milestone's
# API diff reports from real published builds, then writes the agent context. Heavy/networked
# work happens here (pwsh + feed access) so the agent only commits the result and publishes it
# through the native safe outputs.
#
# Ref packs come from the feeds the target pins: the current build from the
# dotnet{major} channel feed, and the baseline (previous prerelease milestone or
# previous-major GA) from dotnet-public. The ApiDiff tool installs from
# dotnet{major}-transport.
#
# Exclusions (apidiff file format: attributes "T:<FullTypeName>" per line;
# assemblies bare name per line):
#   - permanent attributes : release-notes/ApiDiffAttributesToExclude.txt
#   - temporary attributes : <content_dir>/ApiDiffAttributesToExclude.txt (per report)
#   - permanent assemblies : release-notes/ApiDiffAssembliesToExclude.txt (no temporary)
# The permanent + temporary attribute lists are merged into one file passed to the
# tool (the CLI takes a single -eattrs file); the global assemblies file is passed
# as -eas. Pending permanent edits on the PR branch are honored before merge.
#
# Output:
#   incremental     -> release-notes/<mm>/preview/<milestone>/api-diff
#   major-to-major  -> release-notes/<mm>/<mm>.0/api-diff (relocated from the tool's
#                      preview folder when the current endpoint is a prerelease)
#
# Gates (in priority order):
#   BLOCKED      : a non-automation `api-diff` PR already introduces reports under
#                  this target's content_dir -> a human owns this diff; stand down
#                  (produce=false, open/disturb nothing).
#   FAST no-op   : an existing PR whose recorded current_version AND status are
#                  unchanged (and that still carries this target's marker) skips all
#                  work (noop=true).
#   METADATA-only: build unchanged but status flipped (draft->ready) -> refresh PR
#                  body/ready/exclusions WITHOUT the expensive full regeneration.
#   COMPLETE-or-nothing: a full regeneration must produce every non-excluded SDK
#                  report (NETCore + AspNetCore + WindowsDesktop). A non-zero
#                  RunApiDiff exit or any missing SDK report -> produce=false; we
#                  never publish a partial diff, and never disturb an existing PR.
#
# Inputs:
#   TARGET      required  single discovery target (JSON) from api-diff-discover.cs
#   AGENT_DIR   optional  where to write target.json (default /tmp/gh-aw/agent)
#   CONTENT_ROOT optional release-notes content root (default release-notes)
# Environment:
#   API_DIFF_TIMEOUT  optional  seconds for the diff (default 1800)
#   GH_TOKEN          optional  PR lookup
#   GH_RUN_ID         optional  workflow run id for the branch collision suffix
#   GITHUB_REPOSITORY optional  owner/repo for PR/comment lookups
set -euo pipefail

TARGET="${TARGET:?TARGET (discovery JSON) is required}"
AGENT_DIR="${AGENT_DIR:-/tmp/gh-aw/agent}"
CONTENT_ROOT="${CONTENT_ROOT:-release-notes}"
REPO="${GITHUB_REPOSITORY:-}"
mkdir -p "$AGENT_DIR"

# The report-generation timestamp recorded in the PR body's yaml block. Captured before
# generation begins so it reflects when this run started; the manifest validation checks
# that the agent stamps this exact value into the refreshed body.
generated_at="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

jqr() { jq -r "$1" <<<"$TARGET"; }
track="$(jqr '.track')"
major="$(jqr '.major')"
previous_version_milestone="$(jqr '.previous_version_milestone')"
current_version_milestone="$(jqr '.current_version_milestone')"
previous_version="$(jqr '.previous_version')"
previous_feed="$(jqr '.previous_feed')"
current_version="$(jqr '.current_version')"
current_feed="$(jqr '.current_feed')"
content_dir="$(jqr '.content_dir')"
cur_milestone="$(jqr '.cur_milestone')"
desired_branch="$(jqr '.desired_branch')"
status="$(jqr '.status')"
marker_id="$(jqr '.marker_id')"

# content_dir drives destructive filesystem ops (mkdir -p, and rm -rf + mv during the
# major-to-major relocation). It is machine-generated by the discovery step, but validate
# its shape before any rm -rf so a malformed or empty value can never escape the intended
# report directory: require a relative path, no '..' traversal, ending in the '/api-diff'
# leaf that discovery always emits. Fail loudly rather than risk deleting the wrong tree.
case "$content_dir" in
"" | /* | *..*)
	echo "::error::content_dir '${content_dir}' must be a non-empty relative path without '..'; aborting before any filesystem op."
	exit 1
	;;
*/api-diff) ;;
*)
	echo "::error::content_dir '${content_dir}' does not end in '/api-diff'; aborting before any filesystem op."
	exit 1
	;;
esac

# The identity marker lives as a VISIBLE yaml comment inside the PR body's state
# block -- never an HTML comment, since hidden markers trip content scanners. It is
# the stable, machine-readable handle used to find this diff's PR across runs. For
# the cumulative major-to-major diff the marker_id is keyed on the major only, so a
# single evergreen PR is reused as the head milestone advances.
marker="api-diff-marker: ${marker_id}"
perm_attrs="${CONTENT_ROOT}/ApiDiffAttributesToExclude.txt"
perm_asms="${CONTENT_ROOT}/ApiDiffAssembliesToExclude.txt"
temp_attrs="${content_dir}/ApiDiffAttributesToExclude.txt"

# human_version_milestone <version-milestone> -> ".NET 11 Preview 6" / ".NET 10" / ".NET 11 RC 1" / ".NET 11 Alpha 1"
human_version_milestone() {
	local version_milestone="$1" maj ms
	maj="${version_milestone%%-*}"
	maj="${maj%.*}"
	ms="${version_milestone#*-}"
	case "$ms" in
	ga) echo ".NET ${maj}" ;;
	alpha.*) echo ".NET ${maj} Alpha ${ms#alpha.}" ;;
	beta.*) echo ".NET ${maj} Beta ${ms#beta.}" ;;
	preview.*) echo ".NET ${maj} Preview ${ms#preview.}" ;;
	rc.*) echo ".NET ${maj} RC ${ms#rc.}" ;;
	*) echo ".NET ${maj} ${ms}" ;;
	esac
}
prev_human="$(human_version_milestone "$previous_version_milestone")"
cur_human="$(human_version_milestone "$current_version_milestone")"
if [ "$track" = "major-to-major" ]; then
	pr_title="API diff between .NET ${previous_version_milestone%%.*} and .NET ${major%.*}"
else
	pr_title="API diff between ${prev_human} and ${cur_human}"
fi

# ---- 0. Resolve the existing marker PR + external-PR guard ------------------
# Our automation PRs carry the `automation` + `api-diff` labels; every hand-authored
# API diff PR carries `api-diff` (with or without `automation`). One labeled query
# finds them all, and we resolve this target's PR in priority order:
#   (a) OUR PR, matched by its identity marker in the body -> reuse it;
#   (b) a NON-automation `api-diff` PR already introducing reports under this
#       target's content_dir -> a human owns this diff and we stand down (blocked).
existing_pr_number=""
target_branch="$desired_branch"
blocked=false
pr_list_failed=false
if [ -n "${GH_TOKEN:-}" ]; then
	# Candidate PRs: the labeled set, unioned with any PR already on our target branch.
	# Identity is the body marker, not the label -- so if a human strips the `api-diff`
	# label from our PR we must still find it (by branch) rather than open a duplicate.
	# Restrict to PRs targeting main -- our automation only ever opens PRs against main,
	# so a PR from the same head/label that targets a non-main base must never be mistaken
	# for the maintained PR. Filter on --base/base: at the API and re-assert baseRefName in
	# jq so a loose search qualifier can never leak a non-main-base PR into the candidates.
	# Fail closed on a discovery-query failure. The old `|| echo '[]'` made a transient
	# list failure indistinguishable from a genuine empty result; combined with the
	# collision-branch fallback below, that could open a DUPLICATE PR when the target
	# branch already exists. Capture each query's exit status instead and stand down
	# (noop) below when either failed, so nothing is created/updated off a partial read.
	if ! api_diff_prs="$(gh pr list --state open --base main --label api-diff --limit 200 --json number,headRefName,baseRefName,body,labels 2>/dev/null)"; then
		pr_list_failed=true
	fi
	if ! by_branch="$(gh pr list --state open --search "head:$desired_branch base:main" --limit 50 --json number,headRefName,baseRefName,body,labels 2>/dev/null)"; then
		pr_list_failed=true
	fi
	if [ "$pr_list_failed" = true ]; then
		api_diff_prs='[]'
		by_branch='[]'
		echo "::warning::PR discovery query failed for ${desired_branch}; standing down (no PR opened/updated this run, retried next run)."
	fi
	api_diff_prs="$(printf '%s\n%s\n' "$api_diff_prs" "$by_branch" | jq -s 'add | map(select((.baseRefName // "") == "main")) | unique_by(.number)' 2>/dev/null || echo "$api_diff_prs")"
	# Match the identity marker as a WHOLE yaml-comment line ("# <marker>"), not a bare
	# substring: a substring match would let the cumulative marker "...-ga_to_11.0" reuse
	# an incremental first-preview PR whose marker is "...-ga_to_11.0-preview.1". Strip CR
	# (GitHub bodies are CRLF) and trailing whitespace before the exact-line comparison.
	match="$(jq -c --arg m "$marker" 'map(select(.body != null and ((.body | gsub("\r";"") | split("\n") | any(gsub("^[ \t]+|[ \t]+$";"") == "# " + $m))))) | .[0] // empty' <<<"$api_diff_prs")"
	if [ -n "$match" ]; then
		existing_pr_number="$(jq -r '.number' <<<"$match")"
		target_branch="$(jq -r '.headRefName' <<<"$match")"
		echo "::notice::reusing marker PR #${existing_pr_number} on ${target_branch}"
	else
		if git ls-remote --exit-code --heads "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git" "$desired_branch" >/dev/null 2>&1; then
			target_branch="${desired_branch}_${GH_RUN_ID:-$(date +%s)}"
			echo "::notice::${desired_branch} already exists; using collision branch ${target_branch}"
		fi
		# (b) External-PR guard: only when WE don't already own a PR for this diff.
		# A human-authored api-diff PR might touch >100 files, in which case the GraphQL/REST API
		# truncates the `files` array on `gh pr list`. We must fetch the file list via `gh pr view`
		# for each non-automation candidate to accurately detect collisions.
		human_prs="$(jq -r 'map(select(([.labels[].name] | index("automation")) | not)) | .[].number' <<<"$api_diff_prs")"
		for hpr in $human_prs; do
			# Check if this PR touches the target directory. Use awk index()==1 for a
			# literal, start-anchored prefix match: content_dir contains "." (e.g.
			# release-notes/11.0/...) which a grep regex would treat as a wildcard.
			if gh pr view "$hpr" --json files --jq '.files[].path' 2>/dev/null |
				awk -v p="${content_dir%/}/" 'index($0, p) == 1 { found = 1 } END { exit !found }'; then
				blocked=true
				echo "::notice::api-diff PR #${hpr} (non-automation) already introduces reports under ${content_dir}; standing down."
				break
			fi
		done
	fi
fi

# ---- 1. No-op / metadata-only decision -------------------------------------
# Compare against the state the last successful run recorded in the PR body's yaml
# block: current_version, status, and whether the resolved PR still carries this
# target's marker.
noop=false
metadata_only=false
if [ "$pr_list_failed" = true ]; then
	# Discovery failed above; we cannot know whether a PR already exists, so stand down
	# without opening or refreshing anything (generated_at is not advanced; retried next run).
	noop=true
elif [ "$blocked" = true ]; then
	# A human owns this diff; there is nothing for the automation to do.
	noop=true
elif [ -n "$existing_pr_number" ]; then
	body_yaml="$(gh pr view "$existing_pr_number" --json body -q '.body' 2>/dev/null | tr -d '\r' || true)"
	recorded="$(sed -n 's/^[[:space:]]*current-version: "\(.*\)"$/\1/p' <<<"$body_yaml" | head -1)"
	recorded_status="$(sed -n 's/^[[:space:]]*status: "\(.*\)"$/\1/p' <<<"$body_yaml" | head -1)"
	# Whether the resolved PR already carries THIS target's marker. An adopted (human-
	# bootstrapped) PR or one whose marker line a human deleted has no marker yet; we
	# must (re)write it, so such a PR never qualifies for a silent no-op. Uses the same
	# whole-line matcher as the PR resolution above (single source of truth).
	has_marker="$(jq -rn --arg b "$body_yaml" --arg m "$marker" \
		'($b | gsub("\r";"") | split("\n") | any(gsub("^[ \t]+|[ \t]+$";"") == "# " + $m))')"
	if [ "$recorded" = "$current_version" ]; then
		if [ "$recorded_status" = "$status" ] && [ "$has_marker" = true ]; then
			noop=true
			echo "::notice::no-op: ${current_version_milestone} unchanged (${current_version}), status '${status}'."
		else
			metadata_only=true
			echo "::notice::metadata-only: build unchanged; status '${recorded_status:-?}'->'${status}', marker_present=${has_marker}."
		fi
	fi
fi

# ---- 2. Position the working tree on the branch the agent will publish ------
# Incremental (an existing PR): check out the maintained PR branch at its current tip so
# generation writes the refreshed reports onto it and the agent's commit APPENDS to the
# branch (push-to-pull-request-branch fast-forwards it -- no capture/restore, no force).
# Fresh (no PR): detach at the base commit so the agent's commit is a clean child of the
# base that create-pull-request diffs against.
# Reach the branch from the ref the checkout's `fetch: ["*"]` already populated; fall back to
# a tokened fetch (the agent checkout does not persist credentials, so a plain
# `git fetch origin <branch>` neither authenticates nor populates refs/remotes/origin/<branch>).
if [ "$noop" = false ]; then
	if [ -n "$existing_pr_number" ]; then
		if git rev-parse --verify --quiet "refs/remotes/origin/${target_branch}" >/dev/null; then
			git checkout -q -B "$target_branch" "refs/remotes/origin/${target_branch}"
			echo "::notice::checked out maintained PR branch ${target_branch}"
		elif [ -n "${GH_TOKEN:-}" ] && [ -n "$REPO" ] &&
			git fetch --no-tags "https://x-access-token:${GH_TOKEN}@github.com/${REPO}.git" "$target_branch" >/dev/null 2>&1; then
			git checkout -q -B "$target_branch" FETCH_HEAD
			echo "::notice::checked out maintained PR branch ${target_branch} (tokened fetch)"
		else
			echo "::error::could not check out maintained PR branch ${target_branch} for the incremental update."; exit 1
		fi
	else
		git checkout -q --detach
		echo "::notice::detached at the base commit for a fresh api-diff PR."
	fi
fi
mkdir -p "$content_dir"
[ -f "$temp_attrs" ] || : >"$temp_attrs"

# Guarantee every exclusion file ends with a newline before generation merges them
# and before the agent appends new entries. Without this, a repo file whose last
# line has no trailing newline (as `release-notes/ApiDiffAttributesToExclude.txt`
# ships) would concatenate the next appended `T:...` onto the previous entry and
# corrupt the list.
ensure_trailing_newline() {
	local f="$1"
	[ -f "$f" ] && [ -s "$f" ] || return 0
	[ -z "$(tail -c1 "$f")" ] || printf '\n' >>"$f"
}
ensure_trailing_newline "$perm_attrs"
ensure_trailing_newline "$perm_asms"
ensure_trailing_newline "$temp_attrs"

temp_keep="$(mktemp)"
cp "$temp_attrs" "$temp_keep"

# ---- 3. Generate (only on a full-refresh run) ------------------------------
# Skipped for no-op (nothing changed) and for metadata-only (build unchanged, so
# the seeded reports are already correct -- we only refresh body/ready/exclusions).
if [ "$track" = "major-to-major" ] && [ "$cur_milestone" != "ga" ]; then
	tool_output_dir="${CONTENT_ROOT}/${major}/preview/${cur_milestone}/api-diff"
else
	tool_output_dir="$content_dir"
fi

gen_ok=true
if [ "$noop" = false ] && [ "$metadata_only" = false ]; then
	merged_attrs="$(mktemp)"
	[ -f "$perm_attrs" ] && cat "$perm_attrs" >>"$merged_attrs"
	if [ -s "$temp_attrs" ]; then
		grep -vE '^[[:space:]]*(#|$)' "$temp_attrs" >>"$merged_attrs" 2>/dev/null || true
	fi
	# de-duplicate
	sort -u "$merged_attrs" -o "$merged_attrs"

	# RunApiDiff.ps1 resolves a non-rooted exclude-file path relative to its own
	# script dir (release-notes/), so a repo-relative path like
	# release-notes/ApiDiffAssembliesToExclude.txt would double to
	# release-notes/release-notes/... -- pass absolute paths.
	abs_asms="$perm_asms"
	case "$abs_asms" in /*) ;; *) abs_asms="$(pwd)/$abs_asms" ;; esac

	if command -v pwsh >/dev/null 2>&1 && [ -f "${CONTENT_ROOT}/RunApiDiff.ps1" ]; then
		echo "::group::api-diff ${track}: ${previous_version} -> ${current_version}"
		TIMEOUT=()
		command -v timeout >/dev/null && TIMEOUT=(timeout "${API_DIFF_TIMEOUT:-1800}")
		ASMS_ARG=()
		[ -f "$abs_asms" ] && ASMS_ARG=(-AssembliesToExcludeFilePath "$abs_asms")
		# Any SDK download failure inside RunApiDiff is a terminating error, so a
		# non-zero exit means the run is incomplete -- capture it rather than
		# swallowing it, so we never publish a partial diff.
		rc=0
		"${TIMEOUT[@]}" pwsh "${CONTENT_ROOT}/RunApiDiff.ps1" \
			-PreviousVersion "$previous_version" -PreviousNuGetFeed "$previous_feed" \
			-CurrentVersion "$current_version" -CurrentNuGetFeed "$current_feed" \
			-AttributesToExcludeFilePath "$merged_attrs" \
			"${ASMS_ARG[@]}" \
			-CoreRepo "$(pwd)" -InstallApiDiff || rc=$?
		echo "::endgroup::"
		if [ "$rc" -ne 0 ]; then
			gen_ok=false
			echo "::warning::RunApiDiff exited ${rc}; treating this run as an incomplete build (no partial PR will be published)."
		fi
	else
		gen_ok=false
		echo "::warning::pwsh or ${CONTENT_ROOT}/RunApiDiff.ps1 unavailable; cannot generate."
	fi
	rm -f "$merged_attrs"
fi

# ---- 3b. Verify at least one SDK report exists, then relocate major-to-major output -
# RunApiDiff.ps1 hard-fails if any SDK's ref packs can't be downloaded, so a successful
# run means every SDK was compared and a missing per-SDK report is a legitimate
# zero-change result (e.g. WindowsDesktop unchanged this milestone) -- publishable. We
# still require at least one report so an entirely empty result never opens/refreshes a
# PR, and a partially-published build is already caught upstream (RunApiDiff errors, not
# a silently-absent report).
if [ "$noop" = false ] && [ "$metadata_only" = false ]; then
	if [ "$gen_ok" = true ]; then
		present=""
		absent=""
		for sdk in NETCore AspNetCore WindowsDesktop; do
			if [ -n "$(find "${tool_output_dir}/Microsoft.${sdk}.App" -type f -name '*.md' ! -name 'README.md' -print -quit 2>/dev/null)" ]; then
				present="${present} ${sdk}"
			else
				absent="${absent} ${sdk}"
			fi
		done
		if [ -z "$present" ]; then
			gen_ok=false
			echo "::warning::incomplete API diff: no SDK produced a report; not publishing an empty diff."
		elif [ -n "$absent" ]; then
			echo "::notice::no API changes for${absent} this milestone; publishing reports for${present}."
		fi
	fi
	if [ "$gen_ok" = true ] && [ "$track" = "major-to-major" ] && [ "$tool_output_dir" != "$content_dir" ]; then
		echo "::notice::relocating major-to-major output ${tool_output_dir} -> ${content_dir}"
		rm -rf "$content_dir"
		mkdir -p "$(dirname "$content_dir")"
		mv "$tool_output_dir" "$content_dir"
		rmdir "${CONTENT_ROOT}/${major}/preview/${cur_milestone}" 2>/dev/null || true
		# The rolling cumulative diff is milestone-agnostic. RunApiDiff names its reports after
		# the current head build (e.g. "11.0-preview7_Foo.md" plus the "11.0-preview7.md" table
		# of contents that links to them), but this evergreen "(X-1) GA -> X" PR must use the
		# stable "${major}.0" prefix RunApiDiff itself emits once the head reaches GA (matching
		# the shipped 9.0.0_*.md convention). Rewriting the milestone prefix off the report file
		# names and their in-file links keeps advancing the head (preview7 -> preview8 -> ... ->
		# GA) a content-only update instead of a churn that renames every report each milestone.
		stale_prefix="${major}-${cur_milestone}"
		stable_prefix="${major}.0"
		if [ "$stale_prefix" != "$stable_prefix" ]; then
			find "$content_dir" -type f -name "${stale_prefix}*" | while IFS= read -r f; do
				b="$(basename "$f")"
				mv "$f" "$(dirname "$f")/${stable_prefix}${b#"$stale_prefix"}"
			done
			esc="$(printf '%s' "$stale_prefix" | sed 's/\./\\./g')"
			find "$content_dir" -type f -name '*.md' -exec sed -i.bak "s/${esc}/${stable_prefix}/g" {} +
			find "$content_dir" -type f -name '*.md.bak' -delete
		fi
	fi
fi

# Restore the durable per-report temporary list, but keep the file only when it
# actually carries temporary exclusions -- an empty placeholder is committed noise.
cp "$temp_keep" "$temp_attrs"
if ! grep -qE '^[[:space:]]*[^[:space:]#]' "$temp_attrs" 2>/dev/null; then
	rm -f "$temp_attrs"
fi

# ---- 4. Agent target.json --------------------------------------------------
report_count="$(find "$content_dir" -type f -name '*.md' ! -name 'README.md' 2>/dev/null | wc -l | tr -d ' ')"
# produce gate:
#  - blocked / no-op            -> never publish
#  - metadata-only              -> publish iff seeded reports exist (body/ready/feedback refresh)
#  - full refresh               -> publish iff generation completed AND reports exist
# Gating on gen_ok is critical: a failed or incomplete regeneration can leave stale
# or partial seeded reports in content_dir, and we must not publish those.
if [ "$noop" = true ] || [ "$blocked" = true ]; then
	produce=false
elif [ "$report_count" -eq 0 ]; then
	produce=false
	if [ "$metadata_only" = true ]; then
		# A metadata-only refresh requires the existing reports to have been
		# seeded from the branch. Zero reports here means seeding did not run
		# (e.g. the branch fetch failed), so keep the flags consistent instead
		# of emitting produce=false with metadata_only=true, which the agent
		# cannot reconcile.
		metadata_only=false
		echo "::warning::metadata-only refresh for ${current_version_milestone} found no seeded reports; standing down."
	else
		echo "::notice::no reports for ${current_version_milestone} (no build / no API changes); no PR will be opened."
	fi
elif [ "$metadata_only" = true ]; then
	produce=true
elif [ "$gen_ok" = true ]; then
	produce=true
else
	produce=false
fi
temp_excluded='[]'
if [ -s "$temp_attrs" ]; then
	temp_excluded="$(jq -Rsc 'split("\n") | map(select(test("^\\s*(#|$)") | not))' "$temp_attrs" 2>/dev/null || echo '[]')"
	[ -n "$temp_excluded" ] || temp_excluded='[]'
fi

if [ "$status" = "code-complete" ]; then
	status_note="**Ready for Review** — ${cur_human} is code complete (development has moved on to the next major)."
else
	status_note="**Draft** — auto-maintained while ${cur_human} is the in-development frontier."
fi
if [ "$track" = "major-to-major" ]; then
	tldr="Cumulative public API diff **.NET ${previous_version_milestone%%.*} → .NET ${major%.*}**, currently reflecting ${cur_human}. Refreshes as .NET ${major%.*} advances toward release."
else
	tldr="Incremental public API diff **${prev_human} → ${cur_human}**."
fi

jq -n \
	--argjson target "$TARGET" \
	--arg content_dir "$content_dir" \
	--arg perm_attrs "$perm_attrs" \
	--arg perm_asms "$perm_asms" \
	--arg temp_attrs "$temp_attrs" \
	--arg marker "$marker" \
	--arg pr_title "$pr_title" \
	--arg tldr "$tldr" \
	--arg status_note "$status_note" \
	--arg target_branch "$target_branch" \
	--arg existing_pr_number "$existing_pr_number" \
	--argjson produce "$produce" \
	--argjson noop "$noop" \
	--argjson metadata_only "$metadata_only" \
	--argjson blocked "$blocked" \
	--argjson report_count "$report_count" \
	--argjson temp_excluded_attributes "$temp_excluded" \
	--arg generated_at "$generated_at" \
	'$target + {
     content_dir: $content_dir,
     permanent_attributes_file: $perm_attrs,
     permanent_assemblies_file: $perm_asms,
     temporary_attributes_file: $temp_attrs,
     marker: $marker,
     pr_title: $pr_title,
     tldr: $tldr,
     status_note: $status_note,
     target_branch: $target_branch,
     existing_pr_number: $existing_pr_number,
     produce: $produce,
     noop: $noop,
     metadata_only: $metadata_only,
     blocked: $blocked,
     report_count: $report_count,
     temp_excluded_attributes: $temp_excluded_attributes,
     generated_at: $generated_at
   }' >"$AGENT_DIR/target.json"

rm -f "$temp_keep"
echo "=== target.json ==="
jq '.' "$AGENT_DIR/target.json"
echo "noop=${noop} metadata_only=${metadata_only} blocked=${blocked} produce=${produce} reports=${report_count} branch=${target_branch}"

# ---- 5. Always emit a run overview to the job step summary (incl. no-op) ----
# Every worker run -- publish, metadata-only refresh, blocked, or a silent
# no-op -- writes a one-glance summary so the outcome is visible without digging
# through logs.
if [ -n "${GITHUB_STEP_SUMMARY:-}" ]; then
	if [ "$blocked" = true ]; then
		decision="🚫 Blocked — a non-automation \`api-diff\` PR already owns this diff; standing down."
	elif [ "$noop" = true ]; then
		decision="😴 No-op — build unchanged, same status. Nothing to do."
	elif [ "$metadata_only" = true ] && [ "$produce" = true ]; then
		decision="📝 Metadata-only refresh — body/ready/feedback update, no regeneration."
	elif [ "$produce" = true ]; then
		decision="✅ Publish — ${report_count} report file(s) staged."
	else
		decision="⏭️ Nothing to publish — no build available or generation was incomplete."
	fi
	{
		echo "## API Diff -- ${pr_title}"
		echo
		echo "| Field | Value |"
		echo "| --- | --- |"
		echo "| Track | \`${track}\` |"
		echo "| Diff | \`${previous_version_milestone}\` (\`${previous_version}\`) → \`${current_version_milestone}\` (\`${current_version}\`) |"
		echo "| Status | \`${status}\` |"
		echo "| Decision | ${decision} |"
		echo "| Reports | ${report_count} |"
		echo "| Target branch | \`${target_branch}\` |"
		echo "| Existing PR | ${existing_pr_number:-—} |"
		echo "| Generated at | ${generated_at} |"
	} >>"$GITHUB_STEP_SUMMARY"
fi
