<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion Condition="'$(LangVersion)' == ''">default</LangVersion>
    <DefineConstants Condition="'$(LangVersion)' == 'preview'">$(DefineConstants);PREVIEW_SAMPLES</DefineConstants>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="Polyfill.fs" />
    <Compile Include="ClosureOptimization.fs" />
    <Compile Include="Program.fs" />
    <Compile Include="RuntimeAsync.fs" Condition="'$(LangVersion)' == 'preview'" />
    <Compile Include="Srtp.fs" Condition="'$(LangVersion)' == 'preview'" />
    <Compile Include="RecordConstructors.fs" Condition="'$(LangVersion)' == 'preview'" />
    <Compile Include="Preview.fs" Condition="'$(LangVersion)' == 'preview'" />
    <Compile Include="Main.fs" />
  </ItemGroup>
</Project>
