name: Tutorial Bug Report
description: Let us know what issues you're facing when trying to run .NET tutorials on the dot.net website.
title: "[.NET Tutorial]: "
labels: [area-tutorials]
body:
  - type: markdown
    attributes:
      value: |
        We welcome bug reports! Please help us gather the information we need to start the triage process.
  - type: input
    id: url
    attributes:
      label: URL
      description: In what page are you having issues?
      placeholder: https://dotnet.microsoft.com
    validations:
      required: true
  - type: dropdown
    id: os
    attributes:
      label: Operating system
      description: What is your operating system?
      options:
        - Windows
        - macOS
        - Linux
    validations:
      required: true
  - type: input
    id: os-version
    attributes:
      label: More information about your system
      description: |
        Please provide more information on your .NET configuration:
          * OS version, and distro if applicable
          * What is the architecture (x64, x86, ARM, ARM64)?
    validations:
      required: false
  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide details about the problem you're experiencing. Include enough details for us to be able to triage it like exact error message, code sample, or anything else that is relevant.
      placeholder: Description
    validations:
      required: true
  - type: textarea
    id: dotnet-info
    attributes:
      label: dotnet --info
      description: Run the dotnet --info command and copy and paste the results
    validations:
      required: false
