using System;
using System.Collections.Generic;
using System.IO;

public static class Program
{
  public static int Main(string[] args) 
  {
    // Draw a dotnet bot.
    Bot(QuoteOfTheDay());

    return 42; // test pass code
  }

  public static string QuoteOfTheDay()
  {
    var quotes = File.ReadAllLines("quotes.txt");

    return quotes[new Random().Next(0, quotes.Length - 1)];
  }

  public static void Bot(string message) 
  {   
    var _tempForeground = Console.ForegroundColor;
      
    Console.ForegroundColor = ConsoleColor.Yellow;
    Console.WriteLine(message);
    Console.ForegroundColor = ConsoleColor.White;
    Console.WriteLine(@"
        __________________
                              \\
                              \\");
    Console.ForegroundColor = ConsoleColor.Magenta;
    Console.WriteLine(@"
                                  ....
                                  ....'
                                  ....
                                ..........
                            .............'..'..
                        ................'..'.....
                      .......'..........'..'..'....
                      ........'..........'..'..'.....
                    .'....'..'..........'..'.......'.
                    .'..................'...   ......
                    .  ......'.........         .....
                    .                           ......
                    ..    .            ..        ......
                  ....       .                 .......
                  ......  .......          ............
                    ................  ......................
                    ........................'................
                  ......................'..'......    .......
                .........................'..'.....       .......
            ........    ..'.............'..'....      ..........
          ..'..'...      ...............'.......      ..........
          ...'......     ...... ..........  ......         .......
        ...........   .......              ........        ......
        .......        '...'.'.              '.'.'.'         ....
        .......       .....'..               ..'.....
          ..       ..........               ..'........
                  ............               ..............
                .............               '..............
                ...........'..               .'.'............
              ...............              .'.'.............
              .............'..               ..'..'...........
              ...............                 .'..............
              .........                        ..............
                .....");
      
  
  
    Console.ForegroundColor = _tempForeground;
  }
}