name: CoreCI
trigger: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    customBuildTags:
    - 1ES.PT.ViaStartRight
    pool:
      name: NetCore1ESPool-Internal
      image: 1es-windows-2022
      os: windows

    stages:
    - stage: release
      jobs:
      - job: release
        templateContext:
          type: releaseJob
          isProduction: true

        steps:
        # Add release steps below
        - script: echo hello world
          displayName: hello world
