name: CoreCI
trigger: none

resources:
  repositories:
  - repository: 1ESPipelineTemplates
    type: git
    name: 1ESPipelineTemplates/1ESPipelineTemplates
    ref: refs/tags/release

extends:
  template: v1/1ES.Official.PipelineTemplate.yml@1ESPipelineTemplates
  parameters:
    pool:
      name: NetCore1ESPool-Internal
      image: 1es-windows-2022
      os: windows

    stages:
    - stage: cgstage
      jobs:
      - job: cgjob
        templateContext:
          isProduction: true
        steps:
        - task: ComponentGovernanceComponentDetection@0
