<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net11.0</TargetFramework>
    <LangVersion Condition="'$(LangVersion)' == ''">preview</LangVersion>
    <ValidationCase Condition="'$(ValidationCase)' == ''">NamedArguments</ValidationCase>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\Polyfill.fs" />
    <Compile Include="Invalid.fs" Condition="'$(ValidationCase)' == 'NamedArguments'" />
    <Compile Include="Reraise.fs" Condition="'$(ValidationCase)' == 'Reraise'" />
    <Compile Include="CharEnums.fs" Condition="'$(ValidationCase)' == 'CharEnums'" />
    <Compile Include="../RuntimeAsync.fs" Condition="'$(ValidationCase)' == 'RuntimeAsync'" />
    <Compile Include="../Srtp.fs" Condition="'$(ValidationCase)' == 'Srtp'" />
    <Compile Include="../RecordConstructors.fs" Condition="'$(ValidationCase)' == 'RecordConstructors'" />
    <Compile Include="../ClosureOptimization.fs" Condition="'$(ValidationCase)' == 'ClosureOptimization'" />
  </ItemGroup>
</Project>
