name: Check Markdown links

on:
  push:
    paths:
      - '**.md'
  pull_request:
    branches: '**'
    paths:
      - '**.md'

permissions:
  contents: read

jobs:
  markdown-link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2
    - uses: umbrelladocs/action-linkspector@v1
      with:
        config_file: '.linkspector.yml'
        reporter: local
        filter_mode: nofilter
        fail_level: error
