name: No Response

# This workflow closes issues where the original author doesn't respond to a request for more information within the predefined period of time.

# Both `issue_comment` and `scheduled` event types are required for this Action
# to work properly.
on:
  issue_comment:
    types: [created]
  schedule:
    # Schedule for five minutes after the hour, every hour
    - cron: '5 * * * *'

jobs:
  noResponse:
    runs-on: ubuntu-latest
    steps:
      - uses: lee-dohm/no-response@v0.5.0
        with:
          token: ${{ github.token }}
          # Number of days of inactivity before an Issue is closed for lack of response
          daysUntilClose: 7
          # Label requiring a response
          responseRequiredLabel: needs-more-info
          # Comment to post when closing an Issue for lack of response. Set to `false` to disable
          closeComment: >
            This issue has been automatically closed due to no response from the original author.
            Please feel free to reopen it if you have more information that can help us investigate the issue further.
